# Generated by Django 3.0.6 on 2020-06-08 10:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=250)),
                ('user_type', models.CharField(default='client', max_length=10)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
