# Generated by Django 3.0.6 on 2020-06-11 22:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.IntegerField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=250)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
