# Generated by Django 3.0.6 on 2020-06-18 02:40

import api.validations.accounts.account_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200612_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_status',
            field=models.CharField(max_length=20, validators=[api.validations.accounts.account_validation.validate_account_status]),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(max_length=20, validators=[api.validations.accounts.account_validation.validate_account_type]),
        ),
    ]
