# Generated by Django 3.0.6 on 2020-06-26 17:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200618_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(max_length=10)),
                ('account_number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=250)),
                ('old_balance', models.DecimalField(decimal_places=2, max_digits=250)),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=250)),
                ('cashier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
