# Generated by Django 3.0.6 on 2020-07-02 02:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200627_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2034e71f-eaa4-4e27-baba-a9f388a3c920'), editable=False, primary_key=True, serialize=False),
        ),
    ]
