POST http://localhost:9000/api/v1/accounts/ HTTP/1.1
content-type: application/json
Cookie: 

{
    "user_id": "3ffd190a-eb51-48d0-86db-87141de5a313",
    "account_type": "savings",
    "account_status": "draft",
    "balance": 0
}
###

PUT http://localhost:9000/api/v1/account/2121416143/ HTTP/1.1
content-type: application/json
Cookie: 

{
    "account_status": "active",
    "account_type": "savings",
    "balance": 20000
}
###

DELETE http://localhost:9000/api/v1/account/8680558062/ HTTP/1.1
content-type: application/json
Cookie: 
