POST http://localhost:9000/api/v1/auth/signup/ HTTP/1.1
content-type: application/json
Cookie: 

{
    "firstname": "sodiq",
    "lastname": "ishola",
    "password": "olatunde",
    "email": "olatundesodiq@gmail.com",
    "user_type": "staff",
    "is_admin": true
}
###

POST http://localhost:9000/api/v1/auth/signin/ HTTP/1.1
content-type: application/json
Cookie: 

{
    "password": "olatunde",
    "email": "olatundesodiq@gmail.com"
}
